USE university;
DROP TABLE IF EXISTS Degree;
CREATE TABLE Degree (
    `DEGREE_ID` INT,
    `DEGREE_NAME` VARCHAR(80) CHARACTER SET utf8
);
INSERT INTO Degree VALUES (01,'Agriculture, Agriculture Operations, And Related Sciences');
INSERT INTO Degree VALUES (03,'Natural Resources And Conservation');
INSERT INTO Degree VALUES (04,'Architecture And Related Services');
INSERT INTO Degree VALUES (05,'Area, Ethnic, Cultural, Gender, And Group Studies');
INSERT INTO Degree VALUES (09,'Communication, Journalism, And Related Programs');
INSERT INTO Degree VALUES (10,'Communications Technologies/Technicians And Support Services');
INSERT INTO Degree VALUES (11,'Computer And Information Sciences And Support Services');
INSERT INTO Degree VALUES (12,'Personal And Culinary Services');
INSERT INTO Degree VALUES (13,'Education');
INSERT INTO Degree VALUES (14,'Engineering');
INSERT INTO Degree VALUES (15,'Engineering Technologies And Engineering-Related Fields');
INSERT INTO Degree VALUES (16,'Foreign Languages, Literatures, And Linguistics');
INSERT INTO Degree VALUES (19,'Family And Consumer Sciences/Human Sciences');
INSERT INTO Degree VALUES (22,'Legal Professions And Studies');
INSERT INTO Degree VALUES (23,'English Language And Literature/Letters');
INSERT INTO Degree VALUES (24,'Liberal Arts And Sciences, General Studies And Humanities');
INSERT INTO Degree VALUES (25,'Library Science');
INSERT INTO Degree VALUES (26,'Biological And Biomedical Sciences');
INSERT INTO Degree VALUES (27,'Mathematics And Statistics');
INSERT INTO Degree VALUES (29,'Military Technologies And Applied Sciences');
INSERT INTO Degree VALUES (30,'Multi/Interdisciplinary Studies');
INSERT INTO Degree VALUES (31,'Parks, Recreation, Leisure, And Fitness Studies');
INSERT INTO Degree VALUES (38,'Philosophy And Religious Studies');
INSERT INTO Degree VALUES (39,'Theology And Religious Vocations');
INSERT INTO Degree VALUES (40,'Physical Sciences');
INSERT INTO Degree VALUES (41,'Science Technologies/Technicians');
INSERT INTO Degree VALUES (42,'Psychology');
INSERT INTO Degree VALUES (43,'Homeland Security, Law Enforcement, Firefighting And Related Protective Services');
INSERT INTO Degree VALUES (44,'Public Administration And Social Service Professions');
INSERT INTO Degree VALUES (45,'Social Sciences');
INSERT INTO Degree VALUES (46,'Construction Trades');
INSERT INTO Degree VALUES (47,'Mechanic And Repair Technologies/Technicians');
INSERT INTO Degree VALUES (48,'Precision Production');
INSERT INTO Degree VALUES (49,'Transportation And Materials Moving');
INSERT INTO Degree VALUES (50,'Visual And Performing Arts');
INSERT INTO Degree VALUES (51,'Health Professions And Related Programs');
INSERT INTO Degree VALUES (52,'Business, Management, Marketing, And Related Support Services');
INSERT INTO Degree VALUES (54,'History');
