USE university;
DROP TABLE IF EXISTS State;
CREATE TABLE State (
    `state_id` INT,
    `state_name` VARCHAR(30) CHARACTER SET utf8,
    `postcode` VARCHAR(2) CHARACTER SET utf8
);
INSERT INTO State VALUES (1,'Alabama','AL');
INSERT INTO State VALUES (2,'Alaska','AK');
INSERT INTO State VALUES (4,'Arizona','AZ');
INSERT INTO State VALUES (5,'Arkansas','AR');
INSERT INTO State VALUES (6,'California','CA');
INSERT INTO State VALUES (8,'Colorado','CO');
INSERT INTO State VALUES (9,'Connecticut','CT');
INSERT INTO State VALUES (10,'Delaware','DE');
INSERT INTO State VALUES (11,'District of Columbia','DC');
INSERT INTO State VALUES (12,'Florida','FL');
INSERT INTO State VALUES (13,'Georgia','GA');
INSERT INTO State VALUES (15,'Hawaii','HI');
INSERT INTO State VALUES (16,'Idaho','ID');
INSERT INTO State VALUES (17,'Illinois','IL');
INSERT INTO State VALUES (18,'Indiana','IN');
INSERT INTO State VALUES (19,'Iowa','IA');
INSERT INTO State VALUES (20,'Kansas','KS');
INSERT INTO State VALUES (21,'Kentucky','KY');
INSERT INTO State VALUES (22,'Louisiana','LA');
INSERT INTO State VALUES (23,'Maine','ME');
INSERT INTO State VALUES (24,'Maryland','MD');
INSERT INTO State VALUES (25,'Massachusetts','MA');
INSERT INTO State VALUES (26,'Michigan','MI');
INSERT INTO State VALUES (27,'Minnesota','MN');
INSERT INTO State VALUES (28,'Mississippi','MS');
INSERT INTO State VALUES (29,'Missouri','MO');
INSERT INTO State VALUES (30,'Montana','MT');
INSERT INTO State VALUES (31,'Nebraska','NE');
INSERT INTO State VALUES (32,'Nevada','NV');
INSERT INTO State VALUES (33,'New Hampshire','NH');
INSERT INTO State VALUES (34,'New Jersey','NJ');
INSERT INTO State VALUES (35,'New Mexico','NM');
INSERT INTO State VALUES (36,'New York','NY');
INSERT INTO State VALUES (37,'North Carolina','NC');
INSERT INTO State VALUES (38,'North Dakota','ND');
INSERT INTO State VALUES (39,'Ohio','OH');
INSERT INTO State VALUES (40,'Oklahoma','OK');
INSERT INTO State VALUES (41,'Oregon','OR');
INSERT INTO State VALUES (42,'Pennsylvania','PA');
INSERT INTO State VALUES (44,'Rhode Island','RI');
INSERT INTO State VALUES (45,'South Carolina','SC');
INSERT INTO State VALUES (46,'South Dakota','SD');
INSERT INTO State VALUES (47,'Tennessee','TN');
INSERT INTO State VALUES (48,'Texas','TX');
INSERT INTO State VALUES (49,'Utah','UT');
INSERT INTO State VALUES (50,'Vermont','VT');
INSERT INTO State VALUES (51,'Virginia','VA');
INSERT INTO State VALUES (53,'Washington','WA');
INSERT INTO State VALUES (54,'West Virginia','WV');
INSERT INTO State VALUES (55,'Wisconsin','WI');
INSERT INTO State VALUES (56,'Wyoming','WY');
INSERT INTO State VALUES (60,'American Samoa','AS');
INSERT INTO State VALUES (64,'Federated States of Micronesia','FM');
INSERT INTO State VALUES (66,'Guam','GU');
INSERT INTO State VALUES (68,'Marshall Islands','MH');
INSERT INTO State VALUES (69,'Northern Mariana Islands','MP');
INSERT INTO State VALUES (70,'Palau','PW');
INSERT INTO State VALUES (72,'Puerto Rico','PR');
INSERT INTO State VALUES (78,'Virgin Islands','VI');
